"""Optional Metal-backed local serving; no torch dependency or fake logprobs."""
import json
import time
import urllib.error
import urllib.request
from urllib.parse import urlsplit

from config import ROUTE_LOCAL, settings
from schemas import Completion
from generation_context import completion_messages, output_limit


def local_system_prompt(model):
    """Give the model deployment facts it cannot infer from its training."""
    host = urlsplit(settings.ollama_base_url).hostname
    if host in {"127.0.0.1", "localhost", "::1"}:
        location = (
            "This reply is generated locally on the computer running Nana, "
            "through a loopback Ollama server. It is not a cloud API call. "
        )
    else:
        location = (
            "This reply is generated by the configured Ollama server. "
            "Its physical location and model storage are not known from this request. "
        )
    context = (
        "Background runtime facts supplied by Nana, not text to repeat in replies: "
        "Your assistant name is Nana. "
        "When specifically asked your name, simply answer Nana. "
        "You operate inside Nana, a user-built chat application. "
        f"The selected model ID is {model}. "
        "Mention the underlying model ID when specifically asked which model "
        "powers you; your assistant name remains Nana. "
        + location +
        "The app's creator built the application, which is distinct from training "
        "the underlying model. Model files can be stored on an SSD; inference "
        "executes on the host's processor using memory, not on the SSD itself. "
        "Do not invent your developer, hosting provider, hardware or storage path. "
        "When asked about your deployment, use these runtime facts instead of "
        "contradictory identity claims in earlier assistant replies. "
        "Keep these facts in the background. Do not volunteer your name, model ID, "
        "local status, Ollama or server details in ordinary replies or greetings. "
        "Only disclose the specific identity or runtime detail the user asks for. "
        "A greeting needs only a natural brief greeting, with no self-introduction. "
        "In an ongoing conversation, answer the current request directly; do not "
        "restart the conversation or repeat an introduction from earlier replies."
    )
    return "\n\n".join(part for part in (settings.system_prompt, context) if part)


def request(path, payload=None, timeout=120):
    body = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(settings.ollama_base_url.rstrip("/") + path,
                                 data=body, headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as response:
            data = json.load(response)
    except urllib.error.HTTPError as exc:
        raise RuntimeError(f"Ollama returned HTTP {exc.code}; check the model is installed") from None
    except urllib.error.URLError:
        raise RuntimeError("Ollama is unavailable. Start Ollama and install the selected model.") from None
    if data.get("error"):
        raise RuntimeError(str(data["error"]))
    return data


def generate(model, prompt):
    started = time.monotonic()
    messages = completion_messages(prompt, local_system_prompt(model))
    from generation_stream import CURRENT
    if CURRENT.get() is not None:
        return stream_generate(model, messages, CURRENT.get(), started)
    data = request("/api/chat", {"model": model, "messages": messages, "stream": False, "think": False,
                                "options": {"temperature": 0,
                                            "num_predict": output_limit(settings.local_max_new_tokens)}})
    return Completion(text=data["message"]["content"].strip(),
                      prompt_tokens=int(data.get("prompt_eval_count", 0)),
                      completion_tokens=int(data.get("eval_count", 0)),
                      source=ROUTE_LOCAL, model_name=model, provider="local",
                      latency_s=time.monotonic() - started)


def stream_generate(model, messages, stream, started):
    stream.start("local", model)
    payload = {"model": model, "messages": messages, "stream": True, "think": False,
               "options": {"temperature": 0, "num_predict": output_limit(settings.local_max_new_tokens)}}
    req = urllib.request.Request(settings.ollama_base_url.rstrip("/") + "/api/chat",
                                 data=json.dumps(payload).encode(), headers={"Content-Type": "application/json"})
    pieces, final = [], {}
    try:
        with urllib.request.urlopen(req, timeout=settings.request_timeout_s) as response:
            for line in response:
                stream.check()
                data = json.loads(line)
                if data.get("error"):
                    raise RuntimeError(str(data["error"]))
                text = data.get("message", {}).get("content", "")
                if text:
                    pieces.append(text)
                    stream.delta(text)
                if data.get("done"):
                    final = data
                    stream.usage({"prompt_tokens": final.get("prompt_eval_count", 0), "completion_tokens": final.get("eval_count", 0)})
    except urllib.error.URLError:
        raise RuntimeError("Ollama streaming connection failed") from None
    return Completion(text="".join(pieces).strip(), prompt_tokens=int(final.get("prompt_eval_count", 0)),
                      completion_tokens=int(final.get("eval_count", 0)), source=ROUTE_LOCAL,
                      model_name=model, provider="local", latency_s=time.monotonic()-started)
